const sampleData = {
  products: [
    {
      name: 'Nike Air Jordan Retro',
      slug: 'nike-air-jordan-retro',
      category: "Men's Sneakers",
      description:
        'Classic Air Jordan design with premium cushioning and style',
      images: [
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331059/bayro/fqyo8f4bns4rtzdxurn8.jpg',
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331060/bayro/aaerv7kc6c076jixasjd.jpg',
      ],
      price: 1100.99,
      brand: 'Nike',
      rating: 4.9,
      numReviews: 12,
      stock: 7,
      isFeatured: true,
      banner:
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764347164/bayro/odeft7qurafistaszvnp.jpg',
    },
    {
      name: 'Elite Three-Pack Dress Shirts',
      slug: 'elite-three-pack-dress-shirts',
      category: "Men's Dress Shirts",
      description:
        'Pack of three elegant shirts, perfect for formal and office wear',
      images: [
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331115/bayro/yni94nw4l9blajqtdzal.jpg',
      ],
      price: 450.45,
      brand: 'Elite',
      rating: 4.5,
      numReviews: 9,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331175/bayro/jct8omunsngk9yhexstj.webp',
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331176/bayro/mhtlwdjrwxhsgmbki7yy.webp',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331247/bayro/jxyqicnowakffxo4embe.jpg',
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331248/bayro/q8lvyzyfedhja2ovvxz8.jpg',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331296/bayro/ldiyyhsdq0uxm2vvczyv.jpg',
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331298/bayro/rwedckasqxfeefz8dsn8.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331342/bayro/wv4zpsxyd4okhwck8yob.jpg',
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331343/bayro/vaxhrorray4zpjvati2x.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331464/bayro/fcvlhh7ithr4xbevbtgx.jpg',
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331465/bayro/qbkgm5rlr6km5y2f3mus.jpg',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331513/bayro/ybw2v7nr8hfiojaouqkg.webp',
        'https://res.cloudinary.com/ahmed--dev/image/upload/v1764331515/bayro/z8f1hxgm1xls8qkiwdcw.webp',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
