import { hashSync } from 'bcrypt-ts';

const sampleData = {
  user: [
    {
      name: 'Ahmed',
      email: 'ahmed@gmail.com',
      role: 'admin',
      password: hashSync('12345', 10),
    },
    { name: 'Ali', email: 'ali@gmail.com', password: hashSync('12345', 10) },
  ],

  products: [
    {
      name: 'Nike Air Sprint Shoes',
      slug: 'nike-air-sprint-shoes',
      category: "Men's Sneakers",
      description: 'Lightweight running shoes designed for speed and comfort',
      images: [
        '/images/sample-products/p7-1.jpg',
        '/images/sample-products/p7-2.jpg',
      ],
      price: 765.95,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 20,
      stock: 0,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Nike Air Jordan Retro',
      slug: 'nike-air-jordan-retro',
      category: "Men's Sneakers",
      description:
        'Classic Air Jordan design with premium cushioning and style',
      images: [
        '/images/sample-products/p8-1.jpg',
        '/images/sample-products/p8-2.jpg',
      ],
      price: 1100.99,
      brand: 'Nike',
      rating: 4.9,
      numReviews: 12,
      stock: 7,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Elite Three-Pack Dress Shirts',
      slug: 'elite-three-pack-dress-shirts',
      category: "Men's Dress Shirts",
      description:
        'Pack of three elegant shirts, perfect for formal and office wear',
      images: ['/images/sample-products/p9-1.jpg'],
      price: 450.45,
      brand: 'Elite',
      rating: 4.5,
      numReviews: 9,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
